resource_types = [
                ('Audiovisual', 'Audiovisual'), 
                ('Book', 'Book'), 
                ('Booklet', 'Booklet'), 
                ('Collection', 'Collection'),
                ('Computational Notebook', 'Computational Notebook'),
                ('Conference Paper', 'Conference Paper'),
                ('Conference Proceeding', 'Conference Proceeding'),
                ('DataPaper', 'Data Paper'),
                ('Dataset', 'Dataset'),
                ('Dissertation', 'Dissertation'),
                ('Event', 'Event'),
                ('Image', 'Image'),
                ('Interactive Resource', 'Interactive Resource'),
                ('Journal', 'Journal'),
                ('Journal Article', 'Journal Article'),
                ('Model', 'Model'),
                ('Output ManagementPlan', 'Output ManagementPlan'),
                ('Peer Review', 'Peer Review'),
                ('Physical Object', 'Physical Object'),
                ('Preprint', 'Preprint'),
                ('Report', 'Report'),
                ('Service', 'Service'),
                ('Software', 'Software'),
                ('Sound', 'Sound'),
                ('Standard', 'Standard'),
                ('Text', 'Text'),
                ('Workflow', 'Workflow'),
                ('Other', 'Other')
                ] 
                
custom_tags = {
                "Classification Terms differing":[ 
                    'Building research',
                    'Wetland archaeology',
                    'Iconography',
                    'Underwater archaeology'
                ],
                "Disciplines": [
                        'African Archaeology',
                        'Ancient American Archaeology',
                        'Ancient American Studies',
                        'Ancient History',
                        'Ancient Oriental Studies',
                        'Anthropology',
                        'Archaeobotany',
                        'Archaeometry',
                        'Archaeozoology',
                        'Biblical Archaeology',
                        'Byzantine Archaeology',
                        'Byzantine History',
                        'Christian Archaeology',
                        'Epigraphy',
                        'Ethnology',
                        'Experimental Archaeology',
                        'Earth Sciences',
                        'Historical Sciences',
                        'Greek Philology',
                        'Islamic Archaeology',
                        'Islamic History',
                        'Classical Archaeology',
                        'History of Art',
                        'Landscape Archaeology',
                        'Latin Philology',
                        'Aerial Archaeology',
                        'Medieval Archaeology',
                        'Medieval and Modern History',
                        'Natural Sciences',
                        'Numismatics',
                        'Papyrology',
                        'Philology',
                        'Provincial Roman Archaeology',
                        'Prehistoric and historical archaeology',
                        'Sociology',
                        'Near Eastern Archaeology',
                        'History of Science',
                        'Egyptian Philology',
                        'Egyptology'
                ],
                "Methods": [
                        '3D-Documentation',
                        'Analogue documentation',
                        'Analogue photography',
                        'Analogue drawing documentation',
                        'Architectural building documentation',
                        'Excavations',
                        'Soil investigations',
                        'Botanical large-scale residue analysis',
                        'DNA analyses',
                        'Data reuse',
                        'Dendrochronology',
                        'Digital documentation',
                        'Digital photography',
                        'Digital graphic documentation',
                        'Remote sensing',
                        'Field surveys',
                        'Photogrammetry',
                        'Find analysis',
                        'Functional analysis',
                        'GIS analysis',
                        'Geodesy',
                        'Geoelectrics',
                        'Geomagnetics',
                        'Geophysical surveys',
                        'Georadar',
                        'Isotope analysis',
                        'Art historical methods',
                        'Laser scanning',
                        'LiDAR',
                        'Literature research',
                        'Material investigations (inorganic)',
                        'Material investigations (organic)',
                        'Human bone analysis',
                        'Mining archaeology',
                        'Pollen analysis',
                        'Prospecting methods',
                        'RTI',
                        'Radiocarbon dating',
                        'Reconstructions',
                        'Retro-digitisation',
                        'Spatial analysis',
                        'Satellite imagery',
                        'Style criticism',
                        'Surveys',
                        'Thermoluminescence (TL/OSL)',
                        'Animal remains analysis',
                        'Topographic survey',
                        'Topographic survey',
                        'Typology',
                        'Underwater archaeology',
                        'Survey'
                ]
                }